exit
review = Review.find((params[:id]).to_i)
review = Review.find((params[:id]).to_i))
c
User.find_by_username(params[:review][:username])
continue
user_id
exit
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
 params[:review][:restaurant_id] params[:review][:restaurant_id]tion_dispatch/middleware/remote_ip.rb:78:in `call'
exit
review.restaurant_id
review = Review.find((params[:id]).to_i)
Review.find((params[:id]).to_i)
exit
(params[:id]).to_i
(params[:id])/.to_i
(params[:id])/.to_s
params[:id]
params.id
params
exit
params[:review][:restaurant_id] exit
params[:review][:restaurant_id]
params[:review]
[:review]
review
exit
exi
review
rev_id
user_id
exit
params[:review][:restaurant_id]
params[:review][restaurant_id]
(params[:id]).to_i
params[:id]
params[:review][:user_id]
params[:review][:rev_content]
params[:review]
params[:review}
params[:id]
params[:review]
params
params[:review][:id]
continue
/api/reviews/:id(
exit
params[:review][:username]
exit
user.id
user = User.find_by_username(params[:review][:username])
quit
exit'
DETAIL:  Failing row contains (21, asdf, t, null, 1, 2016-05-02 21:17:43.603988, 2016-05-02 21:17:43.603988).
user = PG::NotNullViolation - ERROR:  null value in column "user_id" violates not-null constraint
User.find_by_username(params[:review][:username])
params[:review][:username]
params[:review][:rev_content]
exit
params[:review][:yepp]
params[:review.yepp]
params[:review[:yepp]]
params[:review].yepp
params[:review]
params[:restaurant_id]
params
review_params
